language: android

jdk: oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26
  - extra-android-m2repository

branches:
  only:
  - master

sudo: true

script: sudo bash gradlew assembleDebug

after_success:
- pwd; sudo ls -l ./core/build/outputs/apk/debug/
- cd ..
- sudo git clone https://github.com/TrashboxBobylev/torment-pixel-dungeon.git --branch autobuild --single-branch tormentPD_autobuild
- cd tormentPD_autobuild
- sudo mv ../torment-pixel-dungeon/core/build/outputs/apk/debug/core-debug.apk ./tormentPD.apk
- pwd; sudo ls -l .
- sudo git config --global user.email "travis@travis-ci.org"
- sudo git config --global user.name "Travis CI"
- sudo git remote add origin-master https://${AUTH_KEY}@github.com/TrashboxBobylev/torment-pixel-dungeon > /dev/null 2>&1
- sudo git add ./tormentPD.apk
- sudo git commit --message "Snapshot autobuild N.$TRAVIS_BUILD_NUMBER [ci skip]"
- sudo git push origin-master HEAD:autobuild

notifications:
  email:
    on_success: change
    on_failure: always
