language: android

jdk: oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26
  - extra-android-m2repository

branches:
  only:
  - master

script: sudo bash gradlew assembleDebug

after_success: ls -a; sudo ./push-apk.sh

notifications:
  email:
    on_success: change
    on_failure: always
